### ISSUE TITLE
Resize images

### ISSUE THREAD

**Issue by steveoh** [agrc/turn-gps#2]
I looked at a sample of images and they are all in the megabyte range. This is much too large for the web and storybooks. 

I would recommend resizing these images to something more suitable for website viewing. This process can be automated.

**Comment by rkelson** [comment]
I just threw this together late yesterday. I still have a lot to learn and understand outside of what you have taught me. So understand this is a work in progress and I want to get this repo right before applying it to the story map. Jake has been helping with the desktop interface and your direction will be appreciated. I look forward to learning some new stuff that is not tied to website development.  Go Team!

**Comment by steveoh** [comment]
That was my intent with the issue. The issues will help you keep and organize a list of tasks to do as this progresses.
