### ISSUE TITLE
station kml documents are outdated

### ISSUE THREAD

**Issue by steveoh** [agrc/turn-gps#29]
these should be updated to include the new stations 

refs https://github.com/agrc/gis.utah.gov/pull/2401

**Comment by DenisePeterson** [comment]
The links have been updated to direct to the new KML layers.

**Comment by steveoh** [comment]
We should delete the ones here then to clean up.

**Comment by DenisePeterson** [comment]
They've been deleted.

**Comment by steveoh** [comment]
No they haven't. 
<img width="388" alt="image" src="https://github.com/agrc/turn-gps/assets/325813/86adb0b1-351e-48b1-9aad-f7437b70a83a">
